build:
  nodes:
    analysis:
      environment:
        php:
          version: 5.6.40
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build_failure_conditions:
  - 'elements.rating(< A).new.exists'             # No new classes/methods with a rating below A
  - 'issues.new.exists'                           # No new issues
  - 'project.metric("scrutinizer.quality", < 10)' # Code Quality Rating drops below 10
